import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api } from "../lib/api";

interface VirtualKey { id: string; keyPrefix: string; keySuffix: string; name: string; allowedVariantIds: string | null; status: "active" | "revoked"; revokedAt: string | null; lastUsed: string | null; useCount: number; createdAt: string; }
interface Variant { id: string; name: string; description: string | null; }
function parseAllowed(value: string | null): string[] | null { try { return value ? JSON.parse(value) : null; } catch { return null; } }

export default function KeysPage() {
  const qc = useQueryClient(); const [showCreate, setShowCreate] = useState(false); const [newKey, setNewKey] = useState<string | null>(null);
  const keys = useQuery({ queryKey: ["keys"], queryFn: () => api.get<{ data: VirtualKey[] }>("/admin/keys") });
  const variants = useQuery({ queryKey: ["variants"], queryFn: () => api.get<{ data: Variant[] }>("/admin/variants") });
  const revoke = useMutation({ mutationFn: (id: string) => api.post(`/admin/keys/${id}/revoke`), onSuccess: () => qc.invalidateQueries({ queryKey: ["keys"] }) });
  const remove = useMutation({ mutationFn: (id: string) => api.del(`/admin/keys/${id}`), onSuccess: () => qc.invalidateQueries({ queryKey: ["keys"] }) });
  const namedVariants = (ids: string[] | null) => ids === null ? "全部变体" : ids.length ? ids.map((id) => variants.data?.data.find((variant) => variant.id === id)?.name ?? "已删除变体").join(", ") : "不允许任何变体";
  return <div className="page-stack"><header className="page-header"><div><p className="eyebrow">ACCESS CONTROL</p><h2>虚拟 API Key</h2><p className="page-description">Key 只显示一次明文。创建时可限定它能够调用的变体，撤销后请求会立即被拒绝。</p></div><button className="btn btn-primary" onClick={() => setShowCreate(true)}>新建 Key</button></header>
    {newKey && <section className="secret-panel"><div><p className="eyebrow">仅显示一次</p><strong>请立即保存此 Key</strong><code className="secret-value">{newKey}</code><small>关闭此提示后无法再次读取完整 Key，但可随时撤销它。</small></div><button className="btn" onClick={() => setNewKey(null)}>我已保存</button></section>}
    <section className="panel table-panel"><table className="data-table"><thead><tr><th>名称与标识</th><th>允许的变体</th><th>使用情况</th><th>状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody>{(keys.data?.data ?? []).map((key) => <tr key={key.id}><td><strong>{key.name}</strong><small className="cell-sub"><code>{key.keyPrefix}••••{key.keySuffix}</code></small></td><td className="permission-cell">{namedVariants(parseAllowed(key.allowedVariantIds))}</td><td><small>使用 {key.useCount} 次</small><small className="cell-sub">{key.lastUsed ? `最后使用 ${new Date(key.lastUsed).toLocaleString()}` : "从未使用"}</small></td><td><span className={`badge badge-${key.status === "active" ? "active" : "error"}`}>{key.status === "active" ? "有效" : "已撤销"}</span>{key.revokedAt && <small className="cell-sub">{new Date(key.revokedAt).toLocaleString()}</small>}</td><td>{new Date(key.createdAt).toLocaleString()}</td><td><div className="row-actions">{key.status === "active" && <button className="btn btn-small" disabled={revoke.isPending} onClick={() => { if (confirm("撤销后该 Key 将立即失效，确认继续？")) revoke.mutate(key.id); }}>撤销</button>}<button className="icon-danger" title="删除 Key" disabled={remove.isPending} onClick={() => { if (confirm("永久删除此 Key？")) remove.mutate(key.id); }}>×</button></div></td></tr>)}</tbody></table>{!(keys.data?.data ?? []).length && <div className="empty-state">还没有 Key。创建 Key 后，将它作为 Bearer token 提供给 OpenAI SDK。</div>}</section>{showCreate && <CreateKey variants={variants.data?.data ?? []} onClose={() => setShowCreate(false)} onCreated={(raw) => { setNewKey(raw); setShowCreate(false); qc.invalidateQueries({ queryKey: ["keys"] }); }} />}</div>;
}
function CreateKey({ variants, onClose, onCreated }: { variants: Variant[]; onClose: () => void; onCreated: (key: string) => void }) { const [name, setName] = useState(""); const [restrict, setRestrict] = useState(false); const [allowed, setAllowed] = useState<string[]>([]); const [error, setError] = useState(""); const submit = useMutation({ mutationFn: () => api.post<{ data: { key: string } }>("/admin/keys", { name, allowedVariantIds: restrict ? allowed : undefined }), onSuccess: (result) => onCreated(result.data.key), onError: (e: any) => setError(e.message ?? "创建失败") }); const toggle = (id: string) => setAllowed((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]); return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={(e) => e.stopPropagation()}><div className="modal-title"><div><h3>新建虚拟 Key</h3><p>Key 会在创建成功后显示一次。</p></div><button className="modal-close" onClick={onClose}>×</button></div><div className="field"><label className="label">Key 名称</label><input className="input" placeholder="例如 production-web" value={name} onChange={(e) => setName(e.target.value)} /></div><label className="toggle-control"><input type="checkbox" checked={restrict} onChange={(e) => setRestrict(e.target.checked)} />只允许指定变体</label>{restrict && <div className="field"><label className="label">授权变体</label><div className="selection-list">{variants.map((variant) => <label className="selection-row" key={variant.id}><input type="checkbox" checked={allowed.includes(variant.id)} onChange={() => toggle(variant.id)} /><span><strong><code>{variant.name}</code></strong><small>{variant.description ?? "未填写描述"}</small></span></label>)}{!variants.length && <small className="muted">先创建变体，才能配置精确授权。</small>}</div></div>}{error && <div className="form-error">{error}</div>}<div className="modal-actions"><button className="btn" onClick={onClose}>取消</button><button className="btn btn-primary" disabled={!name || submit.isPending || (restrict && !allowed.length)} onClick={() => submit.mutate()}>{submit.isPending ? "创建中..." : "创建并显示 Key"}</button></div></div></div>; }
